window.tailwind = window.tailwind || {};
tailwind.config = {
          darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "primary": "rgb(var(--primary) / <alpha-value>)",
                      "outline-variant": "rgb(var(--outline-variant) / <alpha-value>)",
                      "surface-container-low": "rgb(var(--surface-container-low) / <alpha-value>)",
                      "on-tertiary-container": "rgb(var(--on-tertiary-container) / <alpha-value>)",
                      "secondary-fixed": "rgb(var(--secondary-fixed) / <alpha-value>)",
                      "inverse-primary": "rgb(var(--inverse-primary) / <alpha-value>)",
                      "primary-container": "rgb(var(--primary-container) / <alpha-value>)",
                      "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
                      "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
                      "on-secondary-fixed-variant": "rgb(var(--on-secondary-fixed-variant) / <alpha-value>)",
                      "surface": "rgb(var(--surface) / <alpha-value>)",
                      "outline": "rgb(var(--outline) / <alpha-value>)",
                      "surface-variant": "rgb(var(--surface-variant) / <alpha-value>)",
                      "surface-tint": "rgb(var(--surface-tint) / <alpha-value>)",
                      "surface-container-high": "rgb(var(--surface-container-high) / <alpha-value>)",
                      "surface-bright": "rgb(var(--surface-bright) / <alpha-value>)",
                      "on-primary": "rgb(var(--on-primary) / <alpha-value>)",
                      "secondary-container": "rgb(var(--secondary-container) / <alpha-value>)",
                      "on-tertiary": "rgb(var(--on-tertiary) / <alpha-value>)",
                      "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
                      "on-error-container": "rgb(var(--on-error-container) / <alpha-value>)",
                      "tertiary-fixed-dim": "rgb(var(--tertiary-fixed-dim) / <alpha-value>)",
                      "secondary-fixed-dim": "rgb(var(--secondary-fixed-dim) / <alpha-value>)",
                      "on-background": "rgb(var(--on-background) / <alpha-value>)",
                      "on-tertiary-fixed": "rgb(var(--on-tertiary-fixed) / <alpha-value>)",
                      "on-primary-fixed-variant": "rgb(var(--on-primary-fixed-variant) / <alpha-value>)",
                      "on-primary-fixed": "rgb(var(--on-primary-fixed) / <alpha-value>)",
                      "error-container": "rgb(var(--error-container) / <alpha-value>)",
                      "on-secondary": "rgb(var(--on-secondary) / <alpha-value>)",
                      "inverse-on-surface": "rgb(var(--inverse-on-surface) / <alpha-value>)",
                      "background": "rgb(var(--background) / <alpha-value>)",
                      "on-primary-container": "rgb(var(--on-primary-container) / <alpha-value>)",
                      "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
                      "primary-fixed": "rgb(var(--primary-fixed) / <alpha-value>)",
                      "surface-dim": "rgb(var(--surface-dim) / <alpha-value>)",
                      "primary-fixed-dim": "rgb(var(--primary-fixed-dim) / <alpha-value>)",
                      "tertiary-container": "rgb(var(--tertiary-container) / <alpha-value>)",
                      "surface-container-lowest": "rgb(var(--surface-container-lowest) / <alpha-value>)",
                      "on-secondary-container": "rgb(var(--on-secondary-container) / <alpha-value>)",
                      "inverse-surface": "rgb(var(--inverse-surface) / <alpha-value>)",
                      "tertiary-fixed": "rgb(var(--tertiary-fixed) / <alpha-value>)",
                      "on-error": "rgb(var(--on-error) / <alpha-value>)",
                      "on-secondary-fixed": "rgb(var(--on-secondary-fixed) / <alpha-value>)",
                      "tertiary": "rgb(var(--tertiary) / <alpha-value>)",
                      "error": "rgb(var(--error) / <alpha-value>)",
                      "secondary": "rgb(var(--secondary) / <alpha-value>)",
                      "on-tertiary-fixed-variant": "rgb(var(--on-tertiary-fixed-variant) / <alpha-value>)"
              },
              "borderRadius": {
                      "DEFAULT": "1rem",
                      "lg": "2rem",
                      "xl": "3rem",
                      "full": "9999px"
              },
              "spacing": {
                      "gutter": "24px",
                      "section-gap": "120px",
                      "container-padding": "24px",
                      "base": "8px"
              },
              "fontFamily": {
                      "label-mono": ["JetBrains Mono"],
                      "body-sm": ["Inter"],
                      "headline-md": ["Inter"],
                      "display-lg": ["Inter"],
                      "display-lg-mobile": ["Inter"],
                      "body-lg": ["Inter"]
              },
              "fontSize": {
                      "label-mono": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "500"}],
                      "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
                      "headline-md": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                      "display-lg": ["80px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}],
                      "display-lg-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                      "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}]
              }
            },
          },
        }
